//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsProg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int deliveryID { get; set; }
        public System.DateTime Will_Order_At { get; set; }
        public Nullable<System.DateTime> Expected_Delivery_Date { get; set; }
        public int Cost { get; set; }
    }
}
