//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsProg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ProductName { get; set; }
        public string ProductType { get; set; }
        public int inStock { get; set; }
        public Nullable<decimal> PricePerUnit { get; set; }
    }
}
