//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsProg
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisAli
    {
        public string Urun_Adi { get; set; }
        public Nullable<int> Satis { get; set; }
        public Nullable<int> Alis { get; set; }
    }
}
